version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - order-service
      - payment-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3003"
    depends_on:
      - order-service
      - rabbitmq

  transaction-service:
    build: ./transaction-service
    ports:
      - "3004:3004"
    depends_on:
      - payment-service
      - rabbitmq

  notification-service:
    build: ./notification-service
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:
